theme: minima
# remote-theme: jekyll/minima@v2.5.1

title: "minima test"
  skin: solarized-dark # classic,dark,solarized,solarized-dark
  # date_format: "%b %-d, %Y"
  social_links:
    # twitter: jekyllrb
    github:  sammaya164
    # facebook: jekyll
    # instagram: jekyll
    # youtube: jekyll
 
plugins:
 - jekyll-minima
 - jekyll-feed
 - jekyll-seo-tag
